### ISSUE TITLE
[BUG] Error message for increasing product quantity above stock

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to increase the quantity of a product above the stock level, we receive a message without information about the available stock
 
<img width="1456" alt="image" src="https://github.com/user-attachments/assets/62b6f7f5-91bc-4c99-a1d3-046f4c77938c">

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by kasztof** [comment]
The `errors` object of `/store-api/checkout/cart/line-item` doesn't contain necessary parameters to display this translation message correctly – `{name}` and `{quantity}`

This is the translation used for this message:
```
"product-stock-reached": "The product {name} is only available {quantity} times"
```

And this is the error object:
```
{
  "message": "The product Greta – Glass drink dispenser 5 l with tap and wooden stand is only available 6 times",
  "code": 0,
  "key": "product-stock-reachedc29ad46d64474ef0b72845832f0d879b",
  "level": 10,
  "messageKey": "product-stock-reached"
}
```

It is used in `ProductItem.vue` component like so: 

```
pushError(t(`errors.${element.messageKey}`, { ...element }));
```

as you can see, the `name` and `quantity` are not passed as the translation snippet arguments. I think it will be hard to resolve without modifying the API responses (adding these parameters).

Is there a reason why in this component a translation snippet `pushError(t(`errors.${element.messageKey}))` was used, instead of displaying the error message from API directly? Then, a simple `pushError(element.message)` should display the correct message – the same that is displayed in the standard storefront.

This is the same issue as in https://github.com/shopware/frontends/issues/1166 and few other error messages.
