### ISSUE TITLE
[BUG] useProduct() delivers manufacturer null on detailpage

### ISSUE THREAD

**Issue by pstoecklTasko** [shopware/frontends#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to find out the manufacturer on the product detail page. I tested it also with standard product detailpage layout from  cms-base package. it doenst work. 

![Screenshot 2024-08-13 101817](https://github.com/user-attachments/assets/1fca51f8-f810-46cb-9fc5-5c3ce177c2c5)

I also tested to overwrite the component and here `useProduct()` returns manufacturer: null. I am tested it also to use ` await useProduct()` with no success.

On the listing page, however, it returns values.

### Expected Behavior

I am expecting data for the manufacturer.

### Environment

```markdown
Packages:
"@shopware-pwa/composables-next": "^1.1.0",
"@shopware-pwa/helpers-next": "^1.0.0",
"@shopware-pwa/nuxt3-module": "^1.0.2",
"@shopware-pwa/types": "^1.0.1",
"@shopware/api-client": "^1.0.1",

Shopware: 6.6.3.0
```

**Comment by mkucmus** [comment]
Hey, due to possible performance impact, some of the associations aren't enabled by default. however you have full control of what is fetched from API by association parameter. For this specific case, you can use `search` method of  `useProductSearch` composable to fetch the product with all related entities, like manufacturer, here's an example: 
![image](https://github.com/user-attachments/assets/7ca59294-6f2a-47b7-9920-9d58ee1ad49c)

if you are using a `vue-demo-store` template, here's the place you can work with: https://stackblitz.com/edit/github-gltuc5?file=components%2FFrontendDetailPage.vue

let us know if this solution works for you and if it's good enough to close the issue :)

**Comment by pstoecklTasko** [comment]
Thanks for fast reply. This solution works partly for me. I can get the name. But still not all manufacturer informations are returning, like media. Here i still get `media: null`. 
I can also see that media is null in your screenshot above. 

Think it would be nice to have a list of all associationss in the documentation.

**Comment by mkucmus** [comment]
> Thanks for fast reply. This solution works partly for me. I can get the name. But still not all manufacturer informations are returning, like media. Here i still get `media: null`. I can also see that media is null in your screenshot above.

this is the case also for `associations` parameter:
![image](https://github.com/user-attachments/assets/8291aed4-170b-42d4-9114-e418379859dd)

and the media appears.

> 
> Think it would be nice to have a list of all associationss in the documentation.

could it be a part of core documentation, I agree. but I have a tip for that: when you see a property with a `null` value - it's potentially the case for association. when the property you need is not preset in the response - that's not possible to load this related entity - simply does not exist.

**Comment by pstoecklTasko** [comment]
Thanks, for that tip! That works for me.
