### ISSUE TITLE
[BUG] [error.vue] Cannot add property data-v-inspector, object is not extensible for VUE-DEMO-STORE

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vue-demo-store is currently not working on stackblitz https://stackblitz.com/github/shopware/frontends/tree/main/templates/vue-demo-store?file=README.md

` ERROR  [error.vue]: Cannot add property data-v-inspector, object is not extensible
`

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by cfreak** [comment]
Some here... does anyone know a solution?

**Comment by mkucmus** [comment]
> Some here... does anyone know a solution?

temporarily I recommend disable `componentInspector` option for devtools:

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  devtools: {
    componentInspector: false, // <-- this one
  },
...
 ```

I found that the problem comes from `CmsElementText.vue` component of `cms-base` package, precisely there might be a bug within `renderHtml` helper in combination of extra attributes taken from devtools when `data-v-inspector` is being added.
