### ISSUE TITLE
(Docu) Types Reference ​

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#133]
At the moment the [types reference page](https://shopware-frontends-docs.vercel.app/packages/types.html) in docu is pretty empty.

We should at least provide a list with all the types and links to github source.
This can also be generated like we did for Composables or API Client Reference.

**Comment by mkucmus** [comment]
Due to the fact the types are not generated from existing TS files, our possibilities to generate the same reference as we did for other packages is limited.

Until we don't have new api-client, I recommend to leave a link to gh sub-package in the docs (github.dev) when an user can easily browse in the types and see everything grouped.
