### ISSUE TITLE
[BUG] useOrderDetails.paymentChangeable is always false

### ISSUE THREAD

**Issue by fabianeichinger** [shopware/frontends#1435]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The computed `paymentChangeable` from `useOrderDetails`  is always false, even if the method may be changed.

### Expected Behavior

The value of `paymentChangeable` from `useOrderDetails` should be true if the payment method on the order can be changed.

### Steps To Reproduce

```
const { loadOrderDetails, paymentChangeable } = useOrderDetails(
  props.orderId,
);
await loadOrderDetails();
paymentChangeable.value // => always false
```

### Anything else?

`checkPromotion` is not sent as part of the request body one the readOrder request. Pretty sure this is a regression caused by the following change, as `checkPromotion` is in `mergedAssociations` but not `mergedAssociations.associations`.
https://github.com/shopware/frontends/commit/19540220d87788eed08991d35aaaead2e18564e5#diff-1aae20791a13b17b807d9677e2a8ba59b0bb6d3aa8716bc0a80d5ed09af61d41L205-R218

**Comment by mkucmus** [comment]
hey! in order to see the paymentChangeable attribute filled with the order ids in the `loadOrderDetails` response, please pass the `checkPromotions: true` flag, If you are using the vue-demo-store template, the proper place is somewhere [here](https://github.com/shopware/frontends/blob/main/templates/vue-demo-store/pages/account/order.vue#L86). 

We are going to revert the change as soon as possible.
