### ISSUE TITLE
Reduce unneccessary API call on client side for useListing

### ISSUE THREAD

**Issue by niklaswolf** [shopware/frontends#147]
I'm wondering how to use `useListing` in a SSR-Environment (in this case Nuxt3).
Because the internal state of the composable regarding the `initialListing` ist stored in `_storeInitialListing`, which **can** be injected. But because this state doesn't get hydrated on the client side, the API-call gets made another time on the client side, which is not necessary if the state could be hydrated.
https://github.com/shopware/frontends/blob/main/packages/composables/src/useListing.ts#L277 

So I'm wondering if there is a clever way to make this work nicely with SSR :)

**Comment by BrocksiNet** [comment]
Hi @niklaswolf 👋 

I created a [branch](https://github.com/shopware/frontends/tree/feat/listing-with-astro) with this [commit](https://github.com/shopware/frontends/commit/c03669f92c9cde7ed038adda9fadea1487185ac8) and tested `useListing` inside the Astro template.

You can try it with:
`git checkout feat/listing-with-astro`
`pnpm run dev --filter=shopware-astro `

So I guess your question is not about SSR in general ... more like how we could reduce this one not needed call that is done on client side again?

Did you already tried with Nuxt `useHydration` [(see Docu)](https://nuxt.com/docs/api/composables/use-hydration)?

**Comment by BrocksiNet** [comment]
Hi @niklaswolf, I was researching today again about this topic. 

Some statements to have us in the same context:
- We need the SSR call for SEO reasons (google bot etc.)
- We need the client-side calls because users want to filter and elements change during client-side usage (navigation)
- So we could save one call that takes between 200ms and 400ms on the first "hard" page load **AND** only when a filter is already set (!) [I measured the setInitialListing function]

The main problem is this part here (_packages/composables/src/useListing.ts_):
```
const allFiltersResult = await searchMethod({
  query: initialListing.currentFilters.search || undefined,
});
initialListing = Object.assign({}, initialListing, {
  aggregations: allFiltersResult?.aggregations,
});
```

Maybe I do not see an easy solution at the moment and will discuss this again with the team.

PS: I was able to manage the data-passing from server to client but then I lost the reactivity. And it is not easy to do this in package cms because some NUXT stuff is missing and the package should work also without NUXT.

**Comment by BrocksiNet** [comment]
Thx to the great @mkucmus he found out that this is totally not need anymore. 🎉 
See his PR ➡ https://github.com/shopware/frontends/pull/255

**Comment by niklaswolf** [comment]
@mkucmus striking again! 🥳 
Maybe you should revisit all your comments in some of your files, maybe some hidden improvement-gems are there to be discovered :P :D

**Comment by mkucmus** [comment]
mhmm, that was an easy task because the API was improved to not narrow down the aggregations, so the additional api call wasn't needed anymore 😎

I would like to have more such improvements which help us to get rid of some old artifacts, and sure, revisit and refresh all logic is always a good idea... we can still ask ourselfs not why, but when 😂
