### ISSUE TITLE
[BUG] useCartItem composable returns invalid values

### ISSUE THREAD

**Issue by ignasradzius** [shopware/frontends#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, currently itemRegularPrice and itemSpecialPrice in useCartItem composable returns the same single unitPrice value.

<img width="937" alt="Screenshot 2023-04-20 at 14 57 36" src="https://user-images.githubusercontent.com/38155746/233359108-e3fc5977-4add-488c-a1cf-4f848c492d09.png">

### Expected Behavior

Since cartItem can have different itemQuantities:
1. I expect that itemRegularPrice will return the price of unit * itemQuantity. 
2. I expect that itemSpecialPrice will return discounted price of unit * itemQuantity.

**Comment by mkucmus** [comment]
hey @ignasradzius, thanks for reporting the issue 💙 

I've added new property named `itemTotalPrice` within #168 which is responsible now for keeping the total price for quantities of a product added to the cart.

I left the regular and special (discounted) price as it was because we don't wont to do any calculations on browser side due to known issues with float and rounding numbers, especially for the prices in ecommerce. So I could only expose what comes from API, as it's our single source of truth. The precision and other currency settings can be also set in admin panel, so it would be hard to mainain the client and backend side - it's easy to forget 🤔 

for special price case you can always do the calculation on your as you have an access to `cartItem` object as well - using the library you can trust in that matter. 

Please leave your feedback if it's that OK 👍🏻 for you or not 👎🏻
