### ISSUE TITLE
[BUG] router-active-class not set on parentNode

### ISSUE THREAD

**Issue by BrocksiNet** [shopware/frontends#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the active class is not set on the parentNode when you visit a child link.

When the first level is active:
![image](https://github.com/shopware/frontends/assets/3763023/4ffbbd35-ed94-4ac7-9791-7c9679c2192a)

When a child link from the first level is active:
![image](https://github.com/shopware/frontends/assets/3763023/bde89e67-4b15-437e-9653-9f9721be07b7)

Related Docs:
- https://nuxt.com/docs/api/components/nuxt-link
- https://router.vuejs.org/api/interfaces/RouterLinkProps.html#activeClass

There is also something in our nuxt config:
```
  router: {
    options: {
      linkExactActiveClass: "text-brand-primary",
    },
  },
```

Related slack discussion:
https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1695566531978429

### Expected Behavior

When you click on a child link in the top navigation the active class is also set on the parent.
This means the child should have an exact active class and parent active class.
This gives the possibility to highlight parentNode when a child is active (currently this is not possible).

### Steps To Reproduce

You can see this in current demo store.

**Comment by mkucmus** [comment]
I can see few obstacles here to make it works as described:

1. dynamic routes (with [...all] placeholder) are not aware of level of nesting by itself, because the nesting is contained in shopware admin panel. So from nuxt/vue router perspective it's just a single, standalone route with no parents -> it's working in another way when we statically define a parent route and subroute, then nuxt knows what the parent route and link is.
2. It's hard to workaround it by comparing a child and parent route paths, because either parent and child can have nothing to do with each other route path, like, parent can be `/clothes` and child category can be `/super-clothes/t-shirts` and simple regex or string comparison won't work in that case.
3. top navigation is out of the category context, and hydrated before we know the active category. that makes the  comparison of current category id (using `_useContext` (or `useCategory` ❔) agains generated link, because the category is not known. so probably it will ends up with `no context` error.

theoretical solutions:
- move category resolution to an upper level of an app (like app.vue or layout 🤔 ), and then provide it to the whole app to enable using it in every lower level of an app.
- todo

**Comment by mdanilowicz** [comment]
https://github.com/nuxt/nuxt/issues/14042#issuecomment-1557380986
