### ISSUE TITLE
Deployable on edge?

### ISSUE THREAD

**Issue by azngeek** [shopware/frontends#49]
What are some known limitations when using Shopware Frontends in a high traffic environment. For example the current PWA solutions requires a lot of resources when deployed in a production environment. 

Basically even with a sep. caching layout for api responses you will be limited by the number of instances you can manage because your servers will run out of memory. 

Making Shopware Frontends deployable on Edge, for example: https://vercel.com/docs/concepts/edge-network/overview would be a major benefit. Is this currently possible as it is basically Nuxt (https://nuxt.com/docs/getting-started/deployment) ?

**Comment by mkucmus** [comment]
Hey @azngeek! Currently project supports deployment on `vercel-edge` for ./templates/vue-demo-store, but you have to disable ssr for nuxt:
```js
//nuxt.config.ts
ssr: false,
nitro: {
   preset: "vercel-edge",
}
```

we need to keep in mind that edge functions have a lot of limitations -> https://vercel.com/docs/concepts/functions/edge-functions/limitations#many-node.js-apis-are-not-available in order to make the solution faster (tl;dr: the environment does not have nodejs but only JavaScript API)

Problem I found was that `useAsyncData` we currently use for page resolving (uses server prefetch mechanism under the hood) does not work well on vercel-edge, and there is a problem with hydration. You can deal with that for example, by enabling `lazy` mode, or disabling `server` for the useAsyncData (globally it's solved by disabling mentioned ssr).

**Comment by BrocksiNet** [comment]
Closed for now. If you have feedback feel free to reopen.
