### ISSUE TITLE
[FEATURE] Wishlist should work with only a product id, not a fully qualified product type

### ISSUE THREAD

**Issue by freb97** [shopware/frontends#526]
### Description

We are using the 'useProductWishlist' composable not only for the product listing where the product is fully available, but also in the cart where we only have access to a line item. Right now we have to use a trick to get the composable working:

```typescript
useProductWishlist(payload as unknown as Ref<Schemas['Product']>)
```

The wishlist composable seems to only obtain the product id internally (correct me if i'm wrong), so would this change make sense?

Before:
```typescript
export function useProductWishlist(
  product: Ref<Schemas["Product"]>,
)
```

After:
```typescript
export function useProductWishlist(
  productId: Ref<string>,
)
```

### Use Case

The useProductWishlist composable would become usable anywhere in the codebase as long as a product id is available, without having to fight against TypeScript, e.g. `payload as unknown as Ref<Schemas['Product']>`.

**Comment by mdanilowicz** [comment]
Hi @freb97, I'm afraid that we cannot change the param type because of the backward compatibility.
But I agree that using the whole object here does not make sense. For now, I added a second type for the parameter and a "constructor" to ensure that using both types does not cause any problems. 

Let me know if this resolves your problem.
