### ISSUE TITLE
[BUG] VITE_ERROR plugin:nuxt:imports-transform for vue-demo-store and vue-blank templates 

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running templates vue-demo-store and vue-blank on stackblitz we get 500
[vite-node] [plugin:nuxt:imports-transform] [VITE_ERROR] virtual:nuxt:./.nuxt/runtime/shopware.plugin.mjs

"Make sure that shopwareEndpoint and shopwareAccessToken are settled in the configuration",
//         "Make sure that shopwareEndpoint and shopwareAccessToken are settled in the configuration",
at virtual:nuxt:./.nuxt/runtime/shopware.plugin.mjs

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by cfreak** [comment]
we are having the same issue. Does someone know how to fix that?

**Comment by mkucmus** [comment]
> we are having the same issue. Does someone know how to fix that?

hey, from my investigation the incorrect import in the plugin was the problem:
```ts
import { defineNuxtPlugin } from "#app";
```

there is some issue when we want to import it from general `#imports`. I'm preparing the fix for that.

Working example with fixed module you can find here: https://stackblitz.com/github/shopware/frontends/tree/fix/ssr-500-vite-import/templates/vue-demo-store?file=modules%2Fnuxt3-module%2Fplugin.ts

**Comment by patzick** [comment]
That's caused by 
![image](https://github.com/shopware/frontends/assets/13100280/00a9e70b-12be-4a84-b17f-ec0b2eae78ee)


fix is on the way: https://github.com/unjs/mlly/pull/232 - as soon as it's released it will work again

**Comment by patzick** [comment]
Back to normal: https://stackblitz.com/github/shopware/frontends/tree/main/templates/vue-demo-store 👍
